### ISSUE TITLE
To bypass null image issue

### ISSUE THREAD

**Issue by andykenward** [patrick91/gatsby-typing-example#1]
@patrick91 For now I've done this

```ts
import GatsbyImage, { FluidObject } from "gatsby-image"
import { oc } from "ts-optchain"

....

const imageFluid = oc(data).placeholderImage.childImageSharp.fluid() || null
  /**
   * The `as FluidObject` is not ideal.
   * The typings for GatsbyImage do not match the
   * typings generated for GatsbyImageSharpFluid
   * Fields can be null from the query but are required for GatsbyImage
   */
  return imageFluid != null ? (
    <GatsbyImage fluid={imageFluid as FluidObject} />
  ) : null
```
See [andykenward/gatsby-starter-default-typescript](https://github.com/andykenward/gatsby-starter-default-typescript/blob/177dfa2376d9a18d2a59c0ca09925d9ec9ddd5fc/src/components/image.tsx#L31-L40)

**Comment by patrick91** [comment]
@andykenward ah thanks! I did this: https://github.com/pythonitalia/pycon/tree/master/frontend/src/node_modules/gatsby-image

and sent a PR to fix it in Gatsby: https://github.com/gatsbyjs/gatsby/pull/17065

hope it gets merged soon :)
